// The open-data lexicon generated by scripts/build-vocabulary-dataset.py (sources: DATA_SOURCES.md). Server-only:
// only the server actions import this, so none of it reaches the browser bundle.
import { classify, type CefrSource, type DiscoveryCategory, type WordClass, type WordLevel } from "./catalog";
import lexicon from "./data/lexicon.json";
import { SENSE_SHARDS } from "./data/senses";

export type LexEntry = { cefr?: WordLevel; cefrSource?: CefrSource; zipf: number; styleBits: number; flags: { vulgar: boolean; insult: boolean; sexual: boolean }; categories: DiscoveryCategory[]; pos: string };
// [part of speech, definition, examples, synonyms, antonyms, related]
export type WordNetSense = [string, string, string[], string[], string[], string[]];

const { meta } = lexicon;
let entries: Map<string, LexEntry> | undefined;
let byCategory: Map<DiscoveryCategory, string[]> | undefined;

// Parsed once per server process (~53k rows, a few tens of milliseconds).
function load() {
  if (entries && byCategory) return { entries, byCategory };
  entries = new Map();
  byCategory = new Map();
  for (const row of lexicon.rows.split("\n")) {
    const [word, cefr, source, zipf, styleBits, flagBits, categoryBits, pos] = row.split("\t");
    const categories = (meta.categories as DiscoveryCategory[]).filter((_, i) => +categoryBits & (1 << i));
    const flags = +flagBits;
    entries.set(word, {
      cefr: (cefr || undefined) as WordLevel | undefined,
      cefrSource: (source || undefined) as CefrSource | undefined,
      zipf: +zipf,
      styleBits: +styleBits,
      flags: { vulgar: !!(flags & meta.flagBits.vulgar), insult: !!(flags & meta.flagBits.insult), sexual: !!(flags & meta.flagBits.sexual) },
      categories,
      pos,
    });
    for (const c of categories) {
      if (!byCategory.has(c)) byCategory.set(c, []);
      byCategory.get(c)!.push(word);
    }
  }
  return { entries, byCategory };
}

export const lexiconEntry = (id: string) => load().entries.get(id);
export const categoryWords = (c: DiscoveryCategory) => load().byCategory.get(c) ?? [];

// CEFR level, rarity, tier and style for a word; undefined when it isn't in the lexicon (e.g. an inflected form).
// ponytail: recomputed per call; filtering the whole General pool costs ~30–40ms per discovery. Index by tier if that grows.
export function classOf(id: string): WordClass | undefined {
  const e = lexiconEntry(id);
  return e && classify(e);
}

const shards = new Map<string, Promise<Record<string, WordNetSense[]>>>();
export async function wordnetSenses(id: string): Promise<WordNetSense[]> {
  const load = SENSE_SHARDS[id[0]];
  if (!load) return [];
  let shard = shards.get(id[0]);
  if (!shard) {
    shard = load().then((m) => JSON.parse(m.default.data));
    shards.set(id[0], shard);
  }
  return (await shard)[id] ?? [];
}
